### ISSUE TITLE
Gateway timeout issue when accessing entities

### ISSUE THREAD

**Issue by deshetti** [factly/dega-gateway#42]
![screen shot 2019-02-24 at 12 16 58 am](https://user-images.githubusercontent.com/10763210/53295910-ff709300-37ca-11e9-9fd0-5d1b17912ac2.png)

The issue could be related to the one mentioned here: https://stackoverflow.com/questions/52625345/jhipster-gateway-forwarding-and-timeout-error

**Comment by deshetti** [comment]
I made the changes the following changes to application.yml in gateway, but when I don't see the values picked up when I check the configuration values from the admin console.

```
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 30000
ribbon:
    ReadTimeout: 60000
    connection-timeout: 3000
    eureka:
        enabled: true
zuul:
    host:
        connect-timeout-millis: 5000
        max-per-route-connections: 10000
        max-total-connections: 5000
        socket-timeout-millis: 60000
    semaphore:
        max-semaphores: 500
```
